apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  ports:
    - port: 80
      #targetPort: 80
    # configurando a porta 30000
    nodePort: 30000
  selector:
    app: first-pod