apiVersion: v1
kind: Pod
metadata:
  name: db.news
  labels:
    app: db-news
spec:
  containers:
    - name: db-news-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      env:
        - name: "MYSQL_ROOT_PASSWORD"
          value:
        - name: "MYSQL_DATABASE"
          value:
        - name: "MYSQL_PASSWORD"
          value:
